In [7]:
# 모듈가져오기 -> pip install numpy
import numpy

#-----------------------------------
# 1) numpy 배열 생성과 기본 활용
#-----------------------------------
# 리스트를 통한 1차원(=1행으로 구성) 배열 만들기
arr = numpy.array([1,3,5,7,9])
print(arr)

# 배열의 크기와 각 원소에 접근하기
# -> 내장함수 len()은 모든 연속성 데이터(문자열, 리스트, 튜플 등)에 사용 가능
size = len(arr)
print("배열의 원소를 %d개 입니다." % size)

# 배열의 원소에 접근하기
# -> 리스트와 마찬가지로 각 원소에 인덱스 번호로 접근 가능.
print(arr[0])
print(arr[1])
print(arr[3])

# 인덱스가 있기 때문에 반복문을 통해서 제어할 각 원소에 접근 가능
for i, v in enumerate(arr):
    print("%d번째 원소 >> %d" %(i, v))

#--------------------------------------------------
# 2) numpy 배열의 특성
#--------------------------------------------------
# 서로 다른 타입의 원소를 갖는 list만들기
# -> 파이썬의 리스트는 서로 다른 타입 허용
arr2 = [1.2, 3, '4']
print(arr2)

# 정수와 실수가 섞인 리스트를 배열로 변환
# -> 배열은 원소의 타입이 서로 다른 것을 허용하지 않음
# -> 가장 포괄적인 형태의 자료형으로 통일함
# -> 여기서는 실수가 범위가 더 크므로 모든 원소가 실수형으로 변환됨
arr3 = numpy.array([1, 2.4, 3, 4.6])
print(arr3)

# 정수, 실수, 문자열이 포함된 리스트를 배열로 변환
# -> 모든 타입이 문자열로 변환되어 있음
arr4 = numpy.array([1.2, 3, '4'])
print(arr4)

# 모든 원소의 타입을 강제로 int(정수)로 지정
# -> 소수점 아래 값들은 모두 버려진다
arr5 = numpy.array([1, 2.4, 3, 4.6], dtype='int')
print(arr5)

#-----------------------------------------------
# 3) 정형화 된 값을 갖는 배열 생성하기
#-----------------------------------------------
# 0부터 15전까지 순차적으로 증가하는 값들을 원소로 갖는 배열
# -> 시작값이 무조건 0부터 시작됨
a = numpy.arange(15)
print(a)

# 100~115전까지 순차적으로 증가하는 값들을 원소로 갖는 배열
b = numpy.array(range(100, 115))
print(b)

# 모든 원소가 실수형 0인 1행 3열 배열 생성
c = numpy.zeros([3])
print(c)

# 모든 원소가 정수형 0인 1행 4열 배열 생성
# -> dtype을 지정하지 않을 경우 기본값은 float(실수)
d = numpy.zeros( [4], dtype='int')
print(d)

# 모든 원소가 실수형 1인 1행 3열 배열
e = numpy.ones([3])
print(e)

# 모든 원소가 정수형 1인 1행 4열 배열
# -> dytpe을 지정하지 않을 경우 기본값은 float(실수)
f = numpy.ones([4], dtype='int')
print(f)

# 모든 원소가 정수형 7인 1행 5열 배열
g = numpy.full([5], 7)
print(g)

# 모든 원소가 실수형 7인 1행 4열 배열
# -> 주의: dtype은 생략할 경우 "int"
h = numpy.full([4],7,dtype='float')
print(h)

[1 3 5 7 9]
배열의 원소를 5개 입니다.
1
3
7
0번째 원소 >> 1
1번째 원소 >> 3
2번째 원소 >> 5
3번째 원소 >> 7
4번째 원소 >> 9
[1.2, 3, '4']
[1.  2.4 3.  4.6]
['1.2' '3' '4']
[1 2 3 4]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114]
[0. 0. 0.]
[0 0 0 0]
[1. 1. 1.]
[1 1 1 1]
[7 7 7 7 7]
[7. 7. 7. 7.]


In [12]:
#---------------------------------------
# 1) numpy 배열의 기초 통계값
#---------------------------------------
# 예제를 위한 배열 구성
grade = numpy.array([82, 77, 91, 88])
print(grade)

# 모든 원소의 합
s1 = numpy.sum(grade)
print("총점: %d" % s1)

# 모든 원소의 평균
s2 = numpy.average(grade)
print("평균: %d" %s2)

# 최대, 최소값
s3 = numpy.max(grade)
s4 = numpy.min(grade)
print("최대값: %d, 최소값: %d " %(s3, s4))

#----------------------------------------
# 2) numpy 배열의 각 원소에 대한 연산
#----------------------------------------
# 모든 원소에 대한 사칙연산 수행
# -> 모든 원소에 대하여 2씩 더함
new1 = grade + 2
print(new1)

# -> 모든 원소에 대하여 5씩 뺌
new2 = grade -5
print(new2)

#--------------------------------------
# 3) numpy 배열끼리의 연산 (1)
#--------------------------------------
# 연산자를 사용한 배열간의 연산 => 위치가 동일한 각 원소끼리 수행된다.
arr1 = numpy.array([10,15,20,25,30])
arr2 = numpy.array([2,3,4,5,6])
print(arr1)
print(arr2)

a = arr1 + arr2
print(a)

b = arr1 + arr2
print(b)

c = arr1 + arr2
print(c)

d = arr1 / arr2
print(d)

#-------------------------------------
# 4) numpy 배열끼리의 연산 (2)
#-------------------------------------
# numpy모듈의 함수를 사용한 배열간의 연산 => 연산자와 동일한 결과
arr1 = numpy.array([10,15,20,25,30])
arr2 = numpy.array([2,3,4,5,6])
print(arr1)
print(arr2)

a = numpy.add(arr1, arr2)
print(a)

b = numpy.subtract(arr1, arr2)
print(b)

c = numpy.multiply(arr1, arr2)
print(c)

[82 77 91 88]
총점: 338
평균: 84
최대값: 91, 최소값: 77 
[84 79 93 90]
[77 72 86 83]
[10 15 20 25 30]
[2 3 4 5 6]
[12 18 24 30 36]
[12 18 24 30 36]
[12 18 24 30 36]
[5. 5. 5. 5. 5.]
[10 15 20 25 30]
[2 3 4 5 6]
[12 18 24 30 36]
[ 8 12 16 20 24]
[ 20  45  80 125 180]


In [16]:
#-----------------------------------
# 1) numpy 배열의 기본 인덱싱, 슬라이싱
#-----------------------------------
# 철수의 1학년~4학년까지의 평균 ㅓㅁ수
grade = numpy.array([82, 77, 91, 88])
print(grade)

# 인덱싱
# -> 2열(0부터 카운트)의 데이터 접근
print(grade[2])

# 슬라이싱
# -> 1열부터 3열 전까지 범위를추출
print(grade[1:3])

# -> 처음부터 2열 전까지 범위를추출
print(grade[:2])

# -> 1열~끝까지 범위를추출
print(grade[1:])

#------------------------------------
# 2) 조건에 맞는 값 추출하기
#------------------------------------
# -> 추출하고자 하는 원본과 같은 사이즈의 배열을 생성한다.
# -> 추출할 값은 True, 그렇지 않으면 False
bool_array = numpy.array([True, False, True, False])

# -> 조건에 맞는 항목만 1차 배열로 추출
result1 = grade[bool_array]
print(result1)

# 80점 이상인지 판별된 조건에 맞는 데이터만 추려냄
result2 = grade[grade >= 80]
print(result2)

# logical_and 함수를 사용하여 80점 이상이고 90점 이하인 데이터만 추려냄
result3 = grade[numpy.logical_and(grade>=80, grade<=90)]
print(result3)

# logical_or 함수를 사용하여 80점 미만이거나 90점 초과인 데이터만 추려냄
result4 = grade[numpy.logical_or(grade<80, grade>90)]
print(result4)

[82 77 91 88]
91
[77 91]
[82 77]
[77 91 88]
[82 91]
[82 91 88]
[82 88]
[77 91]


In [29]:
#-------------------------------------------
# 1) numpy 2차 배열 생성 및 기본 정보 조회
#-------------------------------------------
# 철수의 학년 - 과목별 점수
grade = numpy.array([
    # 열 -> 0  1  2  3
          [98,72,80,64],   # 0행 - kor
          [88,90,80,72],   # 1행 - eng    
          [92,88,82,76]    # 2행 - math 
])
print(grade)

# 배열 정보
# -> 차원크기
print("차원크기:%d" %grade.ndim)
# -> 각 차원의 원소수 튜플로 표시한 것
print(grade.shape)
# -> 각 원소의 타입
print(grade.dtype)

#-----------------------------------------
# 2) 기본 인덱싱과 슬라이싱
#-----------------------------------------
# 정수형 인덱싱
# -> 1행 2열의 데이터 접근 = 80
print(grade[1,2])

# 슬라이싱
# -> 1~3행 전까지, 1~4열 전까지 범위를 추출
print(grade[1:3, 1:4])

# -> 0~2행 전까지, 0~3열 전까지 범위를 추출
print(grade[:2, :3])

# -> 1~끝행, 2~끝열 범위를 추출
print(grade[1:, 2:])

#------------------------------------
# 3) 기초 통계 산출 (max, min, sum, average)
#------------------------------------
# 각 열끼리 더함 (세로로 덧셈) -> 결과 타입은 numpy의 1차
s1 = numpy.sum(grade, axis=0)
print(type(s1))
print(s1)

# 각 행끼리 더함 (가로로 덧셈)
s2 = numpy.sum(grade, axis=1)
print(type(s2))
print(s2)

#----------------------------------
# 4) 조건에 맞는 값 추출하기
#----------------------------------
# bool 형 인덱싱
# -> 추출하고자 하는 원본과 같은 사이즈의 배열
# -> 추출할 값은 True, 그렇지 않으면 False
bool_array = numpy.array([
    [True, False, True, False],
    [True, True, True, False],
    [True, True, True, False]
])

# 조건에 맞는 항목만 1차 배열로 추출
result1 = grade[bool_array]
print(result1)

# 80점 이상인지 판별하여 조건에 맞는 데이터만 추려냄
# -> 추출된 결과는 1차 배열
result2 = grade[grade>=80]
print(result2)

# logical_and 함수를 사용하여 80점 이상이고 90점 이하인 데이터만 추려냄
result3 = grade[numpy.logical_and(grade>=80, grade<=90)]
print(result3)

# logical_or 함수를 사용하여 80점 미만이거나 90점 초과인 데이터만 추려냄
result4 = grade[numpy.logical_or(grade<80, grade>90)]
print(result4)

[[98 72 80 64]
 [88 90 80 72]
 [92 88 82 76]]
차원크기:2
(3, 4)
int32
80
[[90 80 72]
 [88 82 76]]
[[98 72 80]
 [88 90 80]]
[[80 72]
 [82 76]]
<class 'numpy.ndarray'>
[278 250 242 212]
<class 'numpy.ndarray'>
[314 330 338]
[98 80 88 90 80 92 88 82]
[98 80 88 90 80 92 88 82]
[80 88 90 80 88 82]
[98 72 64 72 92 76]
